baseurl: '/resume'

name: Vincent Lee

headline: >-
  Headline goes here. Example: Data Science degree from Harvard with 3 years of experience in software development.
  Passionate about artificial intelligence and more.

contact:
  -
    icon: 'bi bi-globe'
    name: itbaby
    url: 'https://itbaby.github.io/resume/'  # replace with your own address
  -
    icon: 'bi bi-envelope'
    name: jquery@hotmail.com
    url: 'mailto:jquery@hotmail.com'  # replace with your own email
  
  -
    icon: 'bi bi-github'
    name: itbaby
    url: 'https://github.com/itbaby'  # replace with your own address
  -
    icon: 'bi bi-phone-fill'
    name: +86-18042679161
    url: ''  # replace with your own address

    
  
language:
  - English
  - Chinese

techstack:
  -
    icon: angular.png
    name: Angular (8yrs)
    link: 'https://github.com/'  
  -
    icon: js.png
    name: JavaScript(12yrs)
    link: 'https://github.com/' 
  -
    icon: ts.png
    name: JavaScript(7yrs)
    link: 'https://github.com/' 
  -
    icon: aws.png
    name: AWS  (5yrs/Cert)
    link: 'https://github.com/' 
  -
    icon: nodejs.png
    name: Nodejs(10yrs)
    link: 'https://github.com/' 
  -
    icon: git.png
    name: git (7yrs)
    link: 'https://github.com/'  
  -
    icon: jenkins.png
    name: Jenkins (6yrs)
    link: 'https://github.com/' 
  -
    icon: python.png
    name: Python (5yrs)
    link: 'https://github.com/'  
  -
    icon: vue.png
    name: Vue/UNI-APP (2yrs)
    link: 'https://github.com/'    
  -
    icon: svelte.png
    name: Svelte (2yrs)
    link: 'https://github.com/'  
  -
    icon: react.png
    name: React (1yrs)
    link: 'https://github.com/'  
  -
    icon: go.png
    name: GoLang (3yrs)
    link: 'https://github.com/'
  -
    icon: sql.png
    name: Sql (5yrs)
    link: 'https://github.com/'  
  -
    icon: confluence.png
    name: Confluence (6yrs)
    link: 'https://github.com/' 
  -
    icon: jira.png
    name: Jira (6yrs)
    link: 'https://github.com/'    

hobby:
  - Swimming
  - Cooking

########### Education
education:
  -
    icon: jlsfdx.png
    school: Jilin Normal University
    degree: Bachelor's degree, Computer Science and Technology
    loc: JiLin, CN
    time: 2003 ~ 2007 &middot; 4 yrs
    description: >-
      CET: Level 4
      <br>
      Thesis: Your Thesis Title Here
      <br>
      Other information here.
  
########### Experience (optional)
experience:
  -
    icon: fidelity-investments-logo.png
    company: Fidelity Investments
    role: Tech Leader
    loc: DaLian, CN
    time: 2014 ~ now
    description: >-
      Fidelity Investments, formerly known as Fidelity Management & Research (FMR), is an American multinational financial services corporation based in Boston, Massachusetts. Established in 1946, the company is one of the largest asset managers in the world, with $5.4 trillion in assets under management, and $14.1 trillion in assets under administration, as of June 2024, [4] Fidelity Investments operates a brokerage firm, manages a large family of mutual funds, provides fund distribution and investment advice, retirement services, index funds, wealth management, securities execution and clearance, asset custody, and life insurance.
  -
    icon: svs.png
    company: Svs
    role: Tech Leader & Solution Architect
    loc: Dalian, CN
    time: 2011 ~ 2014 &middot; 3yrs
    description: >-
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi condimentum elit justo, vel tristique erat ornare in. Cras ultricies feugiat vehicula. Aenean nulla ipsum, sagittis ac felis vitae, facilisis maximus justo. Nunc ipsum ex, molestie vel velit eu, aliquet posuere velit. In dignissim volutpat ante, non lacinia eros egestas non. Mauris hendrerit orci sit amet metus facilisis, nec sollicitudin justo consectetur. Aenean aliquet velit egestas elementum efficitur. Cras sit amet fringilla arcu.
  -
    icon: huaxin.png
    company: Svs
    role: Tech Leader & Solution Architect
    loc: Dalian, CN
    time: 2008 ~ 2011 &middot; 3yrs
    description: >-
      Dalian Huaxin Computer Technology Co., Ltd. (Dalian Huaxin for short) is a leading supplier of application software products, information services and industry solutions for global customers. After years of development, Dalian Huaxin has grown into a provider of comprehensive solutions from software design, development, testing, implementation to later training, maintenance services and business consulting with software technology as the core. Dalian Huaxin's software technology and information services are applied to multiple industries such as telecommunications, electricity, public, finance, insurance, transportation, logistics, media, manufacturing, etc., helping more than 400 customers at home and abroad to improve work quality and effectively enhance customer value. 

