baseurl: '/resume'

name: Vincent Lee

headline: >-
  Headline goes here. Example: Data Science degree from Harvard with 3 years of experience in software development.
  Passionate about artificial intelligence and more.

contact:
  -
    icon: 'bi bi-globe'
    name: itbaby
    url: 'https://itbaby.github.io/resume/'  # replace with your own address
  -
    icon: 'bi bi-envelope'
    name: jquery@hotmail.com
    url: 'mailto:jquery@hotmail.com'  # replace with your own email
  
  -
    icon: 'bi bi-github'
    name: itbaby
    url: 'https://github.com/itbaby'  # replace with your own address
  -
    icon: 'bi bi-phone-fill'
    name: +86-18042679161
    url: ''  # replace with your own address

    
  
language:
  - English
  - Chinese

techstack:
  -
    icon: angular.png
    name: Angular (8yrs)
    link: 'https://github.com/'  
  -
    icon: js.png
    name: JavaScript(12yrs)
    link: 'https://github.com/' 
  -
    icon: ts.png
    name: JavaScript(7yrs)
    link: 'https://github.com/' 
  -
    icon: aws.png
    name: AWS  (5yrs/Cert)
    link: 'https://github.com/' 
  -
    icon: nodejs.png
    name: Nodejs(10yrs)
    link: 'https://github.com/' 
  -
    icon: git.png
    name: git (7yrs)
    link: 'https://github.com/'  
  -
    icon: jenkins.png
    name: Jenkins (6yrs)
    link: 'https://github.com/' 
  -
    icon: python.png
    name: Python (5yrs)
    link: 'https://github.com/'  
  -
    icon: vue.png
    name: Vue/UNI-APP (2yrs)
    link: 'https://github.com/'    
  -
    icon: svelte.png
    name: Svelte (2yrs)
    link: 'https://github.com/'  
  -
    icon: react.png
    name: React (1yrs)
    link: 'https://github.com/'  
  -
    icon: go.png
    name: GoLang (3yrs)
    link: 'https://github.com/'
  -
    icon: sql.png
    name: Sql (5yrs)
    link: 'https://github.com/'  
  -
    icon: confluence.png
    name: Confluence (6yrs)
    link: 'https://github.com/' 
  -
    icon: jira.png
    name: Jira (6yrs)
    link: 'https://github.com/'    

hobby:
  - Swimming
  - Cooking

########### Education
education:
  -
    icon: jlsfdx.png
    school: Jilin Normal University
    degree: Bachelor's degree, Computer Science and Technology
    loc: JiLin, CN
    time: 2003 ~ 2007 &middot; 4 yrs
    description: >-
      GPA: 4.0/4.0
      <br>
      Thesis: Your Thesis Title Here
      <br>
      Other information here.
  
########### Experience (optional)
experience:
  -
    icon: fidelity-investments-logo.png
    company: Fidelity Investments
    role: Tech Leader
    loc: DaLian, CN
    time: 2014 ~ now
    description: >-
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi condimentum elit justo, vel tristique erat ornare in. Cras ultricies feugiat vehicula. Aenean nulla ipsum, sagittis ac felis vitae, facilisis maximus justo. Nunc ipsum ex, molestie vel velit eu, aliquet posuere velit. In dignissim volutpat ante, non lacinia eros egestas non. Mauris hendrerit orci sit amet metus facilisis, nec sollicitudin justo consectetur. Aenean aliquet velit egestas elementum efficitur. Cras sit amet fringilla arcu.
  -
    icon: svs.png
    company: Svs
    role: Tech Leader & Solution Architect
    loc: Dalian, CN
    time: 2011 ~ 2014 &middot; 2yrs
    description: >-
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi condimentum elit justo, vel tristique erat ornare in. Cras ultricies feugiat vehicula. Aenean nulla ipsum, sagittis ac felis vitae, facilisis maximus justo. Nunc ipsum ex, molestie vel velit eu, aliquet posuere velit. In dignissim volutpat ante, non lacinia eros egestas non. Mauris hendrerit orci sit amet metus facilisis, nec sollicitudin justo consectetur. Aenean aliquet velit egestas elementum efficitur. Cras sit amet fringilla arcu.
  -
    icon: huaxin.png
    company: Svs
    role: Tech Leader & Solution Architect
    loc: Dalian, CN
    time: 2008 ~ 2011 &middot; 2yrs
    description: >-
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi condimentum elit justo, vel tristique erat ornare in. Cras ultricies feugiat vehicula. Aenean nulla ipsum, sagittis ac felis vitae, facilisis maximus justo. Nunc ipsum ex, molestie vel velit eu, aliquet posuere velit. In dignissim volutpat ante, non lacinia eros egestas non. Mauris hendrerit orci sit amet metus facilisis, nec sollicitudin justo consectetur. Aenean aliquet velit egestas elementum efficitur. Cras sit amet fringilla arcu.

########### Publications (optional)
publication:
  -
    title: An Awesome Paper with an Awesome Title 2
    author: Josh Lee
    journal: International Conference on Machine Learning (ICML)
    year: 2022
    link: 'http://arxiv.org/'
  -
    title: An Awesome Paper with an Awesome Title 1
    author: Josh Lee
    journal: International Conference on Learning Representations (ICLR)
    year: 2021
    link: 'http://arxiv.org/'

########### Projects (optional)
project:
  -
    icon: github.svg
    name: awesome-project-one
    link: 'https://github.com/'
    description: |
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi condimentum elit justo, vel tristique erat ornare in. Aenean aliquet velit egestas elementum efficitur. Cras sit amet fringilla arcu.
  -
    icon: github.svg
    name: awesome-project-two
    link: 'https://github.com/'
    description: |
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi condimentum elit justo, vel tristique erat ornare in. Aenean aliquet velit egestas elementum efficitur. Cras sit amet fringilla arcu.
