baseurl: "/resume"

name: Rubin Lee

headline: >-
  10yrs on tech solutions for big finance company, master popular front-end tech solutions. master anguar / design / solutions for global company.
  understand scrum / aws / k8s solutions in products. support global tech solutions for many international companies.

contact:
  - icon: "bi bi-globe"
    name: itbaby
    url: "https://itbaby.github.io/resume/" # replace with your own address
  - icon: "bi bi-envelope"
    name: jquery@hotmail.com
    url: "mailto:jquery@hotmail.com" # replace with your own email

  - icon: "bi bi-github"
    name: itbaby
    url: "https://github.com/itbaby" # replace with your own address
  - icon: "bi bi-phone-fill"
    name: +86-18042679161
    url: "" # replace with your own address

language:
  - English
  - Chinese

techstack:
  - icon: angular.png
    name: Angular (8yrs)
    link: "https://github.com/"
  - icon: js.png
    name: JavaScript(12yrs)
    link: "https://github.com/"
  - icon: ts.png
    name: JavaScript(7yrs)
    link: "https://github.com/"
  - icon: aws.png
    name: AWS  (5yrs/Cert)
    link: "https://github.com/"
  - icon: nodejs.png
    name: Nodejs(10yrs)
    link: "https://github.com/"
  - icon: u3d.png
    name: Unity (3yrs)
    link: "https://github.com/"
  - icon: git.png
    name: git (7yrs)
    link: "https://github.com/"
  - icon: jenkins.png
    name: Jenkins (6yrs)
    link: "https://github.com/"
  - icon: python.png
    name: Python (5yrs)
    link: "https://github.com/"
  - icon: vue.png
    name: Vue/UNI-APP (2yrs)
    link: "https://github.com/"
  - icon: svelte.png
    name: Svelte (2yrs)
    link: "https://github.com/"
  - icon: react.png
    name: React (1yrs)
    link: "https://github.com/"
  - icon: go.png
    name: GoLang (3yrs)
    link: "https://github.com/"
  - icon: sql.png
    name: Sql (5yrs)
    link: "https://github.com/"
  - icon: confluence.png
    name: Confluence (6yrs)
    link: "https://github.com/"
  - icon: jira.png
    name: Jira (6yrs)
    link: "https://github.com/"

hobby:
  - Swimming
  - Cooking

########### Education
